title: Vermintide Snippets
theme: jekyll-theme-time-machine
collections:
  snippets:
    output: true
    layout: default
    permalink: /:title/
#defaults:
#  -
#    scope:
#      path: "_snippets"
#      type: "snippets"
#    values:
#      layout: "default"
