title: Vermintide Snippets
author: https://discord.gg/GAQMw4W
description: >
  A collection of Vermintide snippets. To run them,
  you'll need a mod to execute Lua in-game, such as VermKit.
  (Read the About page for more information.)

theme: minima
header_pages:
  - README.md
  - LICENCE.md

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    default_lang: lua
#    span:
#      line_numbers: false
#    block:
#      line_numbers: true
#      start_line: 1

collections:
  snippets:
    output: true
    permalink: /:title/
  snippets_lua:
    output: true
    permalink: /:title/lua/

defaults:
  -
    scope:
      type: "snippets"
    values:
      layout: "snippet"
  -
    scope:
      type: "snippets_lua"
    values:
      layout: "snippet_lua"
